[tool.poetry]
authors = ["Agustín Covarrubias <agucova@uc.cl>"]
description = ""
name = "reguleque-search"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
typesense = "^0.11.0"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
flake8 = "^3.9.1"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
